resources:

  - name: vijay_artifactory
    type: FileSpec
    configuration:
      sourceArtifactory: s_artifactory
      pattern: "example-repo-local/foo"
      recursive: false

pipelines:

  - name: vijay_pipelines_S_Bash_0129
    steps:
      - name: vijay_artifactory_0129
        type: Bash
        configuration:
          inputResources:
            - name: vijay_artifactory
              trigger: true
        execution:
          onExecute:
            - echo "executing step..."

  - name: vijay_pipelines_S_Bash_0133
    steps:
      - name: vijay_S_Bash_0133
        type: Bash
        configuration:
          inputResources:
            - name: vijay_artifactory
        execution:
          onExecute:
            - echo "executing step..."
            - |
              [ ! -z "$res_vijay_artifactory_sourceArtifactory_user" ]
            - |
              [ ! -z "$res_vijay_artifactory_sourceArtifactory_apikey" ]
            - |
              [ ! -z "$res_vijay_artifactory_operation" ]
            - |
              [ ! -z "$res_vijay_artifactory_sourceArtifactory_url" ]
            - |
              [ ! -z "$res_vijay_artifactory_integrationName" ]
            - |
              [ ! -z "$res_vijay_artifactory_recursive" ]
            - |
              [ ! -z "$res_vijay_artifactory_sourceArtifactory_id" ]
            - |
              [ ! -z "$res_vijay_artifactory_pattern" ]
            - |
              [ ! -z "$res_vijay_artifactory_resourcePath" ]
            - |
              [ ! -z "$res_vijay_artifactory_sourceArtifactory_name" ]
            - |
              [ ! -z "$res_vijay_artifactory_isTrigger" ]
            - |
              [ ! -z "$res_vijay_artifactory_integrationAlias" ]
            - |
              [ ! -z "$res_vijay_artifactory_resourceId" ]
            - |
              [ ! -z "$res_vijay_artifactory_sourceArtifactory_masterName" ]
              
  - name: vijay_pipelines_S_Bash_0130
    steps:
      - name: vijay_S_Bash_0130
        type: Bash
        configuration:
          inputResources:
            - name: vijay_artifactory
              trigger: false
        execution:
          onExecute:
            - echo "executing step..."

