resources:
  - name: S_Bash_0539_FileSpec
    type: FileSpec
    configuration:
      sourceArtifactory: s_artifactory
      aql: '{"items.find":{"name":{"$match":"s_foo"}}}'

  - name: S_Bash_0543_FileSpec
    type: FileSpec
    configuration:
      sourceArtifactory: s_artifactory
      pattern: "test-automation-generic-local/fileSpecBash/s_foo"
      limit: 1
      sortBy:
        - created
        
  - name: S_Bash_0544_FileSpec
    type: FileSpec
    configuration:
      sourceArtifactory: s_artifactory
      pattern: "test-automation-generic-local/fileSpecBash/s_foo"
      limit: 1
      excludePatterns:
        - "test-automation-generic-local/fileSpecBash/pipeInfo.json"
        
  - name: S_Bash_0545_FileSpec
    type: FileSpec
    configuration:
      sourceArtifactory: s_artifactory
      pattern: "test-automation-generic-local/fileSpecBash/s_foo"
      limit: 1
      exclusions:
        - "test-automation-generic-local/fileSpecBash/pipeInfo.json"        

      
      
pipelines:
  - name: pipelines_S_Bash_0539
    steps:
      - name: S_Bash_0539
        type: Bash
        configuration:
          inputResources:
            - name: S_Bash_0539_FileSpec
        execution:
          onExecute:
            - echo "executing step"
            - pushd $res_S_Bash_0539_FileSpec_resourcePath
            - if [ -f "./fileSpecBash/s_foo" ]; then echo "found the file"; fi
            - if [ ! -f "./fileSpecBash/s_foo" ]; then echo "error finding the file"; exit 1; fi            
            - popd 

            
            

  - name: pipelines_S_Bash_0543
    steps:
      - name: S_Bash_0543
        type: Bash
        configuration:
          inputResources:
            - name: S_Bash_0543_FileSpec
        execution:
          onExecute:
            - echo "executing step"
            - ls
            - pushd $res_S_Bash_0543_FileSpec_resourcePath
            - if [ -f "./fileSpecBash/s_foo" ]; then echo "found the file"; fi
            - if [ ! -f "./fileSpecBash/s_foo" ]; then echo "error finding the file"; exit 1; fi  
            - popd
            
  - name: pipelines_S_Bash_0544
    steps:
      - name: S_Bash_0544
        type: Bash
        configuration:
          inputResources:
            - name: S_Bash_0544_FileSpec
        execution:
          onExecute:
            - echo "executing step"
            - pushd $res_S_Bash_0544_FileSpec_resourcePath
            - if [ -f "./fileSpecBash/s_foo" ]; then echo "found the file"; fi
            - if [ -f "./fileSpecBash/pipeInfo.json" ]; then echo "wrong file found"; exit 1; fi
            - if [ ! -f "./fileSpecBash/s_foo" ]; then echo "error finding the file"; exit 1; fi   
            - popd


  - name: pipelines_S_Bash_0545
    steps:
      - name: S_Bash_0545
        type: Bash
        configuration:
          inputResources:
            - name: S_Bash_0545_FileSpec
        execution:
          onExecute:
            - echo "executing step"
            - pushd $res_S_Bash_0545_FileSpec_resourcePath
            - if [ -f "./fileSpecBash/s_foo" ]; then echo "found the file"; fi
            - if [ -f "./fileSpecBash/pipeInfo.json" ]; then echo "wrong file found"; exit 1; fi
            - if [ ! -f "./fileSpecBash/s_foo" ]; then echo "error finding the file"; exit 1; fi  
            - popd
            
