resources:
  - name: S_Bash_0539_FileSpec
    type: FileSpec
    configuration:
      sourceArtifactory: s_artifactory
      aql: '{"items.find":{"name":{"$match":"test*"}}}'
      target: "/setup/"

  - name: S_Bash_0543_FileSpec
    type: FileSpec
    configuration:
      sourceArtifactory: s_artifactory
      pattern: "*/s_foo*"
      limit: 1
      sortBy:
        - created
      target: "/fileSpecBash/"
      
pipelines:
  - name: pipelines_S_Bash_0539
    steps:
      - name: S_Bash_0539
        type: Bash
        configuration:
          inputResources:
            - name: S_Bash_0539_FileSpec
        execution:
          onExecute:
            - echo "executing step"
            - if [ -f "/setup/test*" ]; then echo "found the file"; fi
            - ls
            - cd dependencyState/resources/S_Bash_0539_FileSpec
            - ls
            - pushd $res_S_Bash_0539_FileSpec_resourcePath
            - ls
            - popd 
            - if [ ! -f "/setup/test*" ]; then echo "error finding the file"; exit 1; fi
            
            

  - name: pipelines_S_Bash_0543
    steps:
      - name: S_Bash_0543
        type: Bash
        configuration:
          inputResources:
            - name: S_Bash_0543_FileSpec
        execution:
          onExecute:
            - echo "executing step"
            - if [ -f "*/fileSpecBash/s_foo" ]; then echo "found the file"; fi
            - if [ ! -f "*/fileSpecBash/s_foo" ]; then echo "error finding the file"; exit 1; fi  
            
            
