resources:
  - name: git_vijay
    type: GitRepo
    configuration:
      gitProvider: vijay
      path: vijayreddy1991/run
  
        
  - name: git_repo1
    type: GitRepo
    configuration:
      gitProvider: vijay
      path: vijayreddy1991/runtime
      branches:     
        include: master
#       files:  # optional
#         include: ^pipe.yml$         

pipelines:
  - name: pipelines_vijay
    steps:
      - name: S_Bash1
        type: Bash
        configuration: 
          inputResources:          
            - name: git_vijay              
        execution:
          onExecute:
            - echo "executing step..."
            - printenv
            
      - name: S_Bash2
        type: Bash
        configuration: 
          inputResources:          
            - name: git_repo1 
          inputSteps:
            - name: S_Bash1 
        execution:
          onExecute:
            - echo "executing step..."
            - printenv
