pipelines:
  - name: pipelines_vijay
    steps:
      - name: S_Bash1
        type: Bash
        configuration: 
          runtime:
            type: host        
        execution:
          onExecute:
            - echo "executing step..."
            - printenv  
