resources:
  - name: git_vijay
    type: GitRepo
    configuration:
      gitProvider: vijay
      path: vijayreddy1991/run
      branches:     
        include: master

pipelines:

  - name: vijay_super
    steps:

      - name: restore_pipelines1
        type: Bash 
        configuration: 
          timeoutSeconds: 10    
          inputResources:          
            - name: git_vijay         
        execution:
          onExecute:
            - printenv  
            - sleep 120
#             - printen
