resources:
  - name: vijay
    type: GitRepo
    configuration:
      gitProvider: vijay
      path: vijayreddy1991/run           
      
pipelines:
  - name: test1
    steps:
      - name: test
        type: Bash
        configuration:
          integrations:
            - name: vijay
          inputResources:
            - name: vijay
            
        execution:
          onExecute: 
            - pushd $res_vijay_resourcePath 
#             - mkdir savetests
#             - pushd savetests
#             - pwd
#             - touch test.xml
#             - echo "hello frog" > test.xml    
#             - ls
#             - popd
#             - python -m py_compile calc.py
#             - pip install --upgrade pip
#             - hash -d pip
#             - pip install pytest           
# #             - py.test --verbose --junit-xml test-reports/results.xml test_calc.py
# #             - save_tests $res_vijay_resourcePath/savetests/test.xml            
#             - popd

      - name: test2
        type: Bash
        configuration:
          integrations:
            - name: vijay
          inputSteps:
            - name: test
          inputResources:
            - name: vijay                
        execution:
          onExecute:
            - printenv
#             - pushd $res_vijay_resourcePath
#             - python -m py_compile calc.py
#             - pip install --upgrade pip
#             - hash -d pip
#             - pip install pytest           
# #             - py.test --verbose --junit-xml test-reports/results.xml test_calc.py
#             - save_tests $res_vijay_resourcePath/jfrog         
#             - popd

      - name: test3
        type: Bash
        configuration:
          integrations:
            - name: vijay
          inputResources:
            - name: vijay
          inputSteps:
            - name: test2          

        execution:
          onExecute:
            - pushd $res_vijay_resourcePath
#             - touch test.xml
#             - echo "fgjhkggfyifyfhgfghjyity" > test.xml
#             - python -m py_compile calc.py
#             - pip install --upgrade pip
#             - hash -d pip
#             - pip install pytest           
#             - py.test --verbose --junit-xml test-reports/results.xml test_calc.py
#             - save_tests $res_vijay_resourcePath/test.xml  
#             - cat test.xml
#             - ls -la
#             - popd
           


            
            
          
