resources:
  - name: git_vijay
    type: GitRepo
    configuration:
      gitProvider: vijaykp
      path: vijayreddy1991/run
      branches:     
        include: master

pipelines:

  - name: vijay_pipeline_power
    steps:

      - name: restore_pipelines
        type: Bash 
        configuration:         
          inputResources:          
            - name: git_vijay         
        execution:
          onExecute:
            - printenv  

            
          
          
