

pipelines:

  - name: vijay_pipeline_power
    steps:

      - name: restore_pipelines
        type: Bash
        configuration:       
        execution:
          onExecute:
            - printenv  

            
          
          
