resources:
  - name: git_vijay
    type: GitRepo
    configuration:
      gitProvider: vijay
      path: vijayreddy1991/run
      branches:     
        include: master

pipelines:

  - name: vijay_super
    steps:

      - name: restore_pipelines1
        type: Bash 
        configuration:         
          inputResources:          
            - name: git_vijay         
        execution:
          onExecute:
            - printenv  
            - sleep 60
#             - printen
       
#   - name: vijay_project_Admin
#     steps:

      - name: restore_pipelines2
        type: Bash 
        configuration:         
          inputResources:          
            - name: git_vijay         
        execution:
          onExecute:
            - printenv   
            - sleep 60

#   - name: vijay_Admin
#     steps:

      - name: restore_pipelines3
        type: Bash 
        configuration:         
          inputResources:          
            - name: git_vijay         
        execution:
          onExecute:
            - printenv 
            - sleep 60
