

pipelines:

  - name: vijay_pipeline_power
    steps:

      - name: restore_pipelines
        type: Bash    
        execution:
          onExecute:
            - printenv  

            
          
          
