resources:
  - name: vijay
    type: GitRepo
    configuration:
      gitProvider: vijay_gitHub
      path: vijayreddy1991/run           
      
pipelines:
  - name: test1
    steps:
      - name: test
        type: Bash
        configuration:
          integrations:
            - name: vijay_gitHub
          inputResources:
            - name: vijay
            
        execution:
          onExecute: 
            - pushd $res_vijay_resourcePath    
            - python -m py_compile calc.py
            - pip install --upgrade pip
            - hash -d pip
            - pip install pytest           
            - py.test --verbose --junit-xml test-reports/results.xml test_calc.py
            - save_tests $res_vijay_resourcePath            
            - popd

      - name: test2
        type: Bash
        configuration:
          integrations:
            - name: vijay_gitHub
          inputSteps:
            - name: test
          inputResources:
            - name: vijay                
        execution:
          onExecute:
            - printenv
            - pushd $res_vijay_resourcePath
            - python -m py_compile calc.py
            - pip install --upgrade pip
            - hash -d pip
            - pip install pytest           
            - py.test --verbose --junit-xml test-reports/results.xml test_calc.py
            - save_tests $res_vijay_resourcePath/jfrog         
            - popd

      - name: test3
        type: Bash
        configuration:
          integrations:
            - name: vijay_gitHub
          inputResources:
            - name: vijay
          inputSteps:
            - name: test2          

        execution:
          onExecute:
            - pushd $res_vijay_resourcePath
            - touch test.xml
            - echo "fgjhkggfyifyfhgfghjyity" > test.xml
            - python -m py_compile calc.py
            - pip install --upgrade pip
            - hash -d pip
            - pip install pytest           
            - py.test --verbose --junit-xml test-reports/results.xml test_calc.py
            - save_tests $res_vijay_resourcePath/test.xml  
            - cat test.xml
            - ls -la
            - popd
           
      - name: power
        type: Bash
        configuration:        
          integrations:
            - name: vijay_gitHub
          inputResources:
            - name: vijay
            
        execution:
          onExecute: 
            - pushd $res_vijay_resourcePath    
            - python -m py_compile calc.py
            - pip install --upgrade pip
            - hash -d pip
            - pip install pytest           
            - py.test --verbose --junit-xml test-reports/results.xml test_calc.py
            - save_tests $res_vijay_resourcePath            
            - popd

      - name: power2
        type: bash
        configuration:
          integrations:
            - name: vijay_gitHub
          inputSteps:
            - name: power
          inputResources:
            - name: vijay                
        execution:
          onExecute:
            - printenv
            - pushd $res_vijay_resourcePath
            - python -m py_compile calc.py
            - pip install --upgrade pip
            - hash -d pip
            - pip install pytest           
            - py.test --verbose --junit-xml test-reports/results.xml test_calc.py
            - save_tests $res_vijay_resourcePath/jfrog         
            - popd

      - name: power3
        type: Bash
        configuration:      
          integrations:
            - name: vijay_gitHub            
          inputResources:
            - name: vijay
          inputSteps:
            - name: power2         

        execution:
          onExecute:
            - pushd $res_vijay_resourcePath
            - python -m py_compile calc.py
            - pip install --upgrade pip
            - hash -d pip
            - pip install pytest           
            - py.test --verbose --junit-xml test-reports/results.xml test_calc.py
            - save_tests $res_vijay_resourcePath/test-reports/jfrog.yml  
            - popd
            


